### ISSUE TITLE
Unable to specify ReportSection 

### ISSUE THREAD

**Issue by glenn-lake** [taarskog/crm-powerbi-viewer#12]
Is there anyway to be able to specify a specific page emulating the click through from a dashboard tile to report from within native PowerBI with the CRM powerbi viewer solution.

We would see the need in two ways 

1)- when we host a PowerBi Report object on CRM dashboard, we may wish to default to specific page.
2) - when clicking on powerbi tile on crm dashboard, or form, it should be able to drill to the correct page within the report

Eg - in PowerBi, the behaviour is to add a URL suffix of     /ReportSection1   /ReportSection2 etc to represent the page numbers.

Is there anyway to achieve this - particularly for defaulting a page number on the report component.

thanks

**Comment by taarskog** [comment]
Thank you for the feedback and input to improvements.

Currently not supported so in the short term you need to fork the code and add the logic yourself. I am working on a new version where I intend to use a new API that allows for more interaction with the embedded Power BI report/tile. I will try to implement your asks in that version.

**Comment by taarskog** [comment]
Added support for specifying page in url. New url format is:

[viewer.html?type=report&id=_**REPORT_ID**_&pageName=_**pagename**_&showFilterPane=_**true**_&showNavPane=_**true**_]()

Also added support for handling click events in tiles, dashboards and reports.

Included in next release.
