### ISSUE TITLE
Reporting non CRM data within CRM

### ISSUE THREAD

**Issue by sudmanche** [taarskog/crm-powerbi-viewer#13]
Hi, 
sorry to ask, but I am new to Power BI. I would like to create reports on non CRM data, and then expose them in CRM by passing a parameter which would link he data.
For example, sales are done in an external system, and rather than importing the data into a CRM entity, the data could be pushed into Power BI to be reported on. Then in CRM I could show sales reports per customer, and per salesperson etc.
Is this possible, and if so is your crm powerbi viewer the approach I should use. In theory it looks like it may be possible to me.

many thanks. sudmanche

**Comment by taarskog** [comment]
Hi Sudmanche and thank you for considering Power BI Viewer.

It is definitively possible and for the time-being I believe the approach taken by Power BI Viewer is the only option you have. I expect support for this to be added to Dynamics 365 out-of-the-box in a future release but no details/roadmap have been communicated by Microsoft so far.

You can easily filter on form attributes and you may even create your own logic for filtering if you require more advanced filters. How to do this is documented on http://crm-powerbi-viewer.heiigjen.com/pages/filter-reports.html
