### ISSUE TITLE
Issues configuring

### ISSUE THREAD

**Issue by rupesh03** [taarskog/crm-powerbi-viewer#15]
Hi

Sorry if this is not the right place to write this . I like the solutions and trying to use it .I followed all the documentation steps . I first installed v8 but it was not working at all .Then i installed version 7 .First it said the azure reply address in not matching . i then configured a reply address in azure. 

Now when i open the configuration page .It opens up but keeps on loading records .But nothing happens. Can you please help me out on how to debug the issue. i got a dynamics 365 online account that i am using at the moment.

![image](https://user-images.githubusercontent.com/30341353/28462995-ec168b96-6e15-11e7-934e-579ebf7822bf.png)
![capture](https://user-images.githubusercontent.com/30341353/28463005-faa8dbbe-6e15-11e7-8807-99c5c3ae480d.PNG)

**Comment by taarskog** [comment]
As this is a new installation I recommend starting with v0.5 and then follow the new installation guide to verify your steps.

**Comment by taarskog** [comment]
Did it work with v0.5?

Also see #16 as the suggested solution probably applies to your issue as well (though moving to v0.5 is still highly recommended)

**Comment by taarskog** [comment]
No response. Assuming solution is similar to #16. Documentation have been updated with the missing step.

**Comment by rupesh03** [comment]
Hi sorry for the delay . thanks for the prompt response I am on holiday . I will test it once I get back and let you know .Really appreciate your prompt response
--
