### ISSUE TITLE
Last step issue

### ISSUE THREAD

**Issue by ClementineSabbe** [taarskog/crm-powerbi-viewer#16]
Hi,

I found the solution of power BI Viewer which seems to be very usefull for me, and I decided to use it. But I have some problems with the installation. I didn't found the solution in other posts so if it's the case, I'm sorry.
I followed all the steps of the configuration document but when I open the solution in the CRM, in the "configuration" window this message appears, and I don't know how to resolve it.
I have got a dynamics 365 online account, and I downloaded the v0.5.0
Thank you!

![image](https://user-images.githubusercontent.com/30409812/28525153-876571a6-7083-11e7-9b24-fe833dc0b24f.png)

**Comment by taarskog** [comment]
Most likely an issue with the documentation. Can you try to press [Grant Permissions] shown to the right of step 9 in the screenshot.

![](http://crm-powerbi-viewer.heiigjen.com/assets/images/v1.0/aad/aad-add-app-permissions.png)

**Comment by ClementineSabbe** [comment]
Thank you, your solution works perfectly!

**Comment by taarskog** [comment]
Glad to hear it worked!

**Comment by rupesh03** [comment]
Hi sorry for the delay . thanks for the prompt response I am on holiday . I will test it once I get back and let you know .Really appreciate your prompt respnse
