### ISSUE TITLE
Mobile report visualization

### ISSUE THREAD

**Issue by SimonGiubs** [taarskog/crm-powerbi-viewer#17]
Hi, this is not a proper issue but..
the solution works fine for web visualization; is there any way to enable the resource for tablet too? I'm trying to find out a solution but looks like there are some authentication issue.
Have yout already tried it and can you give me a hint of how to do it?

S

**Comment by taarskog** [comment]
Unfortunately that is currently not possible ref. known issues on https://www.microsoft.com/en-us/dynamics/crm-customer-center/iframe-and-web-resource-support-in-dynamics-365-for-tablets.aspx:

> Authentication for embedded sites isn’t available.
