### ISSUE TITLE
Handling Mouse Events

### ISSUE THREAD

**Issue by peterloudon** [taarskog/crm-powerbi-viewer#18]
In your Enhancements list for Version 0.50, you say "Open related Dynamics 365 records when clicking on data in a report". Do you have an example of how you have implemented this?

Alternatively, do you have an example of handling the tileClicked event, or any similar mouse interaction, please?

**Comment by taarskog** [comment]
Have not gotten around to create a sample of this yet, but you should be able to find information to get you started at:
- http://crm-powerbi-viewer.heiigjen.com/pages/advanced-config.html
- https://microsoft.github.io/PowerBI-JavaScript/demo/dataselection.html

**Comment by peterloudon** [comment]
Hi @taarskog 

Thank you for your feedback. I have reviewed the links you have provided, but they have brought me no closer to a solution. My scenario is:

1. I am using a report in place of a tile because I cannot filter a tile.
2. When a user clicks anywhere on the report (as tile) I want to take that user to a full report in its own browser window.
3. The best way I can find to do this is to handle the Data Selected event and open the viewer as a Web Resource in response (the subject of my other query).
4. This is potentially confusing because selecting a particular data element suggests to the user that the resulting display relates only to the selected element. It would be better if I could intercept the click event anywhere on the display area, but this seems to be blocked by the Allowed Events parameter.

If you see anything that I am overlooking, I would be grateful if you would point it out.

**Comment by taarskog** [comment]
Embedding a single visual from a report is a fairly new functionality in the Power BI client that may be the way to go. Currently crm-powerbi-viewer does not support visuals, but will look into adding support... Seems you can then both get support for filtering on a "tile" (visual) and probably be able to catch the item clicked so you can filter on it when opening the full report.

Details: https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embed-Single-Visual

**Comment by taarskog** [comment]
It is now possible to embed a single report visual. That combined with listening on the event `dataSelected` should make it possible to solve this request and multiple others (such as opening related record when a table row is selected in PowerBI.
