### ISSUE TITLE
Trouble Signing In on Power Bi Viewer Solution's Configuration Page 

### ISSUE THREAD

**Issue by vdahiya08** [taarskog/crm-powerbi-viewer#20]
Hi 

We are facing this issue of not able to Sign In to Power BI after importing and configuring the solution provided. 
As per the Blog, we were able to achieve till the Power BI Sign In Account. The credentials which do have Power BI Rights were not able to get Signed In. Please see the Screenshots.

Can you help providing some insights about what should i ensure to get the solution's feature in place.

![image](https://user-images.githubusercontent.com/34435379/33820112-b67985e6-de73-11e7-8ac3-4ad6128f0e8a.png)

**Comment by taarskog** [comment]
Hi,

If you look at the text in the popup message you'll see that you don't have the correct reply address. You probably entered/misspelled the address on step 5 on http://crm-powerbi-viewer.heiigjen.com/pages/azure-ad.html.

To fix it go to Azure AD and update **Reply URLs** with the correct URL: https://internalcrm.mpgbis.com/*

**Comment by vdahiya08** [comment]
Hi Trond

Thank you for your prompt response. The query is now resolved.


Thanks and Regards
Vandana Dahiya
CRM Consultant
Support : 1300 662 983
E: vandana.dahiya@dynamicssquare.com<mailto:vandana.dahiya@dynamicssquare.com>
W: www<applewebdata://E99EDC56-A8EF-4E98-9A09-A386602932C0/www.dynamicssquare.com>.dynamicssquare.com<applewebdata://E99EDC56-A8EF-4E98-9A09-A386602932C0/www.dynamicssquare.com>

[cid:293E5825-C55E-415C-B85C-2B7B7C29C907]
