### ISSUE TITLE
The reply address does not match the reply addresses configured for the application

### ISSUE THREAD

**Issue by stevencastilloxsystem** [taarskog/crm-powerbi-viewer#21]
With the configuration in the Webpage (AAD and CRM Dynamics) appear the error: "We received an incorrect request."

The reply address 'https://company.crm2.dynamics.com//WebResources/his_/powerbi/admin.html' does not match the reply addresses configured for the application

**Comment by taarskog** [comment]
Same issue as #20. Need to set a reply address in AAD matching the CRM address. Also, note the use of *-notation in the docs.
