### ISSUE TITLE
401: Unauthorized - Error: null when in power bi viewer configuration

### ISSUE THREAD

**Issue by gregmhoffmann** [taarskog/crm-powerbi-viewer#23]
I looked through the other issues and tried a few things like granting permissions but I keep getting this error.  Screenshot's for reference.
![image](https://user-images.githubusercontent.com/38106721/38370951-f2d88cca-38b0-11e8-8003-7650462db7f3.png)

![image](https://user-images.githubusercontent.com/38106721/38370986-03383958-38b1-11e8-9729-f821cec0d2b8.png)

![image](https://user-images.githubusercontent.com/38106721/38370997-0b96a3fa-38b1-11e8-90ba-401251d7b3b3.png)

Thank you!

**Comment by gregmhoffmann** [comment]
Needed a power bi pro license.  Ill see my way out.

**Comment by taarskog** [comment]
Hmmm.... Didn't need a pro license previously - but needed to open PowerBI.com and login once to make it work. May be that they have changed the licensing for embedding...
