### ISSUE TITLE
Safari not loading the application

### ISSUE THREAD

**Issue by N-karjalainen** [taarskog/crm-powerbi-viewer#24]
Hey,

I got the solution working perfectly on our CRM instance.

However our Mac users are currently unable to use the solution. The PowerBI tiles embedded with viewer.html show up white on dashboards.

I can see the Webresource title and the PowerBI Refresh button, but the content of tiles or reports does not load.

**Comment by taarskog** [comment]
Are they able to view the same tiles (i.e. dashboards) by going directly to [powerbi.com](https://powerbi.microsoft.com)? If that works please have them retry in CRM.

If that does not help you need to look at the console log in the browser to see if there are any relevant messages there (you may need to increase the logging level in his_/powerbi/scripts/config.js).

**Comment by taarskog** [comment]
Closing. No response in 3 weeks...
