### ISSUE TITLE
To the Author

### ISSUE THREAD

**Issue by stjacobo** [taarskog/crm-powerbi-viewer#25]
What is your understanding of the licensing requirements for PowerBI using your product within the confines of Dynamics 365?   Can they use the free PowerBI or do they need the Professional License of PowerBI for each one of the Users?

**Comment by taarskog** [comment]
I am no licensing expert so you should verify this with your licensing partner and/or Microsoft. With that said it seems they recently changed the requirements so more users can stay with free and still consume reports published to a Workspace (previously this required a pro license) - see more at https://docs.microsoft.com/en-us/power-bi/service-free-vs-pro.

From the linked page:
> If an app is published, and the app workspace it is for is assigned to Premium capacity, Free users can consume those apps.
