### ISSUE TITLE
Data Filtering

### ISSUE THREAD

**Issue by SergioRota** [taarskog/crm-powerbi-viewer#27]
I followed the Trond’s guide and I see my Power BI report in Dynamics 365 dashboards and forms 🙂

I have some issues about data filtering: following your guide I created the web resource for Account filtering (new_accountfilter.js); I adding this in his_/powerbi/scripts/config.js:

![image](https://user-images.githubusercontent.com/40394191/41599716-48b644a8-73d4-11e8-913b-21db71fffbf2.png)

is this correct?

After in the form I modified the web resource properties adding &customFn=Samples.Filters.filterOnAccount
and selected the option to pass the record Id

![image](https://user-images.githubusercontent.com/40394191/41599760-69709f90-73d4-11e8-82eb-737f82b4a1c4.png)

Thanks
Sergio

**Comment by taarskog** [comment]
No it is not correct - I assume you followed the guide on http://crm-powerbi-viewer.heiigjen.com/pages/advanced-config.html?<br/>
<br/>
If you look at the last of the 2 script references you see the one you should use when referencing a web resource:<br/>
`"../../prefix_/scripts/eventhandlers.js?ver=1"`<br/>
<br/>
So in your case it will be:<br/>
`"../../new_/accountfilter.js?ver=1"`<br/>
<br/>  
Don't forget the last double quote (").

**Comment by taarskog** [comment]
I may have mislead you. You config should maybe be `"../../new_accountfilter.js?ver=1"`. Verify by checking the url of your web resource and adjust as needed.

If you still have trouble please take a look at the debug console (F12). Errors should be logged there. If you are not able to find the issue I suggest you post a screenshot here...

Also verify that the table name match what you have in your report (including casing).

**Comment by SergioRota** [comment]
The Web Resource with Account Filter function is: **new_accountfilter**
The reference in custom_script about his_/powerbi/scripts/config.js is **"../../**new_accountfilter**.js?ver=1"** 

**_.js_** isn't a part of name of my web resource but have I to insert it in the reference?


About the table name in PowerBI:
![image](https://user-images.githubusercontent.com/40394191/41655020-b0a2be72-748b-11e8-8b8d-2a46e0b79b27.png)

Here's  the console errors:
![image](https://user-images.githubusercontent.com/40394191/41655055-d71b96c8-748b-11e8-97fa-2f7cedbab292.png)

Thanks
Sergio

**Comment by taarskog** [comment]
No in that case you should leave it out. I use .js as a convention on all my JavaScript resources.

**Comment by SergioRota** [comment]
Ok, I corrected the web resource.

now these error occur:
![image](https://user-images.githubusercontent.com/40394191/41661908-0c6abbf6-74a0-11e8-8343-c03d54b94d71.png)

**Comment by taarskog** [comment]
Try with the browser in incognito mode (may be a caching issue)… Also try to bump the version `?ver=2`

**Comment by SergioRota** [comment]
Always the same

Does the Web Resource about account filtering correct?

```
window.Samples = window.Samples || {};
Samples.Filters = Samples.Filters || {};
/**
 * Filter on user by name whenever a specific page is shown.
 * 
 * Note: This resets the filter whenever the user navigates to the specific page. 
 * Remove the event logic and set the filter once to avoid resetting on every navigation.
 * 
 * Suggested modifications:
 * - In your own code you should check against page name and not displayname to avoid 
 *   breaking the code if someone changes the displayname
 * - Filters should be on ID and not name
 * - Using Xrm get name/id from current user or owner if view is embedded to a form.
 */
Samples.Filters.filterOnAccount = function (report) {
    report.on("pageChanged", function(event) {
        let page = event.detail.newPage;
        console.log(`Page changed to '${page.displayName}' (${page.name})`);

        if (page.displayName === "Pagina") {
var accId = window.parent.Xrm.Page.data.entity.getId();
accId = accId.replace('{','').replace('}','');
            const filter = {
                $schema: "http://powerbi.com/product/schema#basic",
                target: {
                    table: "accounts",
                    column: "accountid"
                },
                operator: "In",
                values: [accId]
            };

            page.setFilters([filter]);
        }
    });
}
```

My goal is open account form and view a report with only the information about this account (account id)

Thanks
Sergio

**Comment by lumaluma124** [comment]
Hi, i am trying to filter my report by URL. When I try it directly in the webbrowser the filter works fine. but when i add it to the parameter section it doesnt. i did change the ?filter to &filter. do i have to take care of anything else? I really dont know why it doesnt work...
I tried the static version and the custom function js too. nothing works...

**Comment by taarskog** [comment]
Think I found your bug. Just went through the process and it is working well for me.

The issue is with your config. **crm-powerbi-viewer** supports multiple custom scripts. Thus the value `custom_scripts` is expected to be an array.

Yours:
```
	// Array of custom scripts to load. Functions in these scripts can be referenced for report filtering etc.
    custom_scripts: "../../new_/accountfilter?ver=1"
```

Should be:
```
	// Array of custom scripts to load. Functions in these scripts can be referenced for report filtering etc.
    custom_scripts: ["../../new_/accountfilter?ver=1"]
```

May consider adding support for a string here, but for now you need to add the brackets **[ ]**.

**Comment by SergioRota** [comment]
I Trond, sorry but I don't see my report filtered.

I resummarize my steps:

Hi Alex, can you show me yours steps to filtering PowerBI Report?

I followed the powerbiviewer documentation but I don't able to see my report filtered.
My steps:

1) Registration in Azure A, import PowerBIViewer, creation solution named PowerBI Viewer Config and add exiting web resource named his_/powerbi/scripts/config.js; replace the auth client id.

2) copy report configuration value from PowerBIViewer Solution, add web resource to account form with web recource his_/powerbi/viewer.html

I see the report in my account form

3) Create a javascript webresource (new_/script/powerbifilter.js) to filtering account id: 


window.Samples = window.Samples || {};
Samples.Filters = Samples.Filters || {};
/**
 * Filter on user by name whenever a specific page is shown.
 * 
 * Note: This resets the filter whenever the user navigates to the specific page. 
 * Remove the event logic and set the filter once to avoid resetting on every navigation.
 * 
 * Suggested modifications:
 * - In your own code you should check against page name and not displayname to avoid 
 *   breaking the code if someone changes the displayname
 * - Filters should be on ID and not name
 * - Using Xrm get name/id from current user or owner if view is embedded to a form.
 */
Samples.Filters.filterOnAccount = function (report) {
    report.on("pageChanged", function(event) {
        let page = event.detail.newPage;
        console.log(`Page changed to '${page.displayName}' (${page.name})`);

        if (page.displayName === "Pagina") {
var accId = window.parent.Xrm.Page.data.entity.getId();
accId = accId.replace('{','').replace('}','');
            const filter = {
                $schema: "http://powerbi.com/product/schema#basic",
                target: {
                    table: "accounts",
                    column: "accountid"
                },
                operator: "In",
                values: [accId]
            };

            page.setFilters([filter]);
        }
    });
}


4) Add a reference to the new web resource in crm-powerbi-viewer config: 

.....
	// Array of custom scripts to load. Functions in these scripts can be referenced for report filtering etc.
    custom_scripts: ["https://mycrmname.crm4.dynamics.com//WebResources/new_/script/powerbifilter.js?ver=1"]
};

5) add &customFn=<functionname> to the web resource custom parameter:

type=report&id=2e990cc3-c0d7-43d7-9e73-05b9ea789c94&groupId=256f1295-28e8-43a9-9ebd-592e86eecd26&pageName=&showFilterPane=true&showNavPane=true&customFn=Samples.Filters.filterOnAccount

I view the report but It doesn't filtered by account Id

Thanks
Sergio

**Comment by SergioRota** [comment]
It works =D

Thanks you!
