### ISSUE TITLE
Error message on configuration page

### ISSUE THREAD

**Issue by rsilver875** [taarskog/crm-powerbi-viewer#28]
Imported the solution (v1.0).  Seemed to import fine but configuration page says "An error has occurred.  Please try again and finally contact your administrator. More details may be found in the debug console (if appropriate logging level has been set)." 

Running Microsoft Dynamics 365 Version 1612 (9.0.2.449) (DB 9.0.2.449) online.
Image of message attached. ![pbiviewer image 1](https://user-images.githubusercontent.com/17501394/41988845-601d8e02-7a0b-11e8-94c1-6147e6f21f60.png)

Any suggestions appreciated!

Thanks!

**Comment by taarskog** [comment]
As the message say - take a look at the debug console (press F12). My best guess is that you have forgotten quotes (") around the client id in the config file. If that is not the case and the debug console does not provide hints I suggest increasing the log level to verbose.
