### ISSUE TITLE
Prompts For License

### ISSUE THREAD

**Issue by pjmcewan** [taarskog/crm-powerbi-viewer#30]
This is a great tool.  I thought since it's using Power BI Embed that the users that view it don't need a Power BI Pro license.  Is that the case or is something wrong with my configuration?

**Comment by taarskog** [comment]
This is not Power BI Embed for customers - its purpose is to embed data for internal users at your organization (for details take a look at https://docs.microsoft.com/en-us/power-bi/developer/embedding).

The licensing model for Power BI changed a while back and I have heard (but not tested) that a pro user can share a report to free users. See related #25.
