### ISSUE TITLE
Blank configuration page

### ISSUE THREAD

**Issue by MarianneLilholt** [taarskog/crm-powerbi-viewer#31]
Hi Trond
I get a blank configuration page in the solution - in both IE and Chrome.
First it says loading for a few seconds - and then a blank page.
![screenhunter 1035](https://user-images.githubusercontent.com/35331117/43307830-b3a0b3ca-917f-11e8-8aa3-e73c3a25c9e3.png)
![screenhunter 1034](https://user-images.githubusercontent.com/35331117/43307836-b8636d62-917f-11e8-9fdc-ccfbcf63bd59.png)
Any suggestions?

**Comment by taarskog** [comment]
Have you performed an initial login at [powerbi.com](https://app.powerbi.com/?noSignUpCheck=1)?
If yes, then my best guess is that you need to do 15b as described on http://crm-powerbi-viewer.heiigjen.com/pages/azure-ad.html.
Could also be licensing - are you using Pro or Premium?

Also check the logs (press F12) and verify that there are no error messages...

**Comment by MarianneLilholt** [comment]
Thank you. I had used the other simplified flow. Going to the other flow - and granting permissions did the job. Thank you.

**Comment by taarskog** [comment]
Great. Thank you for the update - need to update the documentation it seems...
