### ISSUE TITLE
GroupID used in parameters

### ISSUE THREAD

**Issue by NunezJr** [taarskog/crm-powerbi-viewer#32]
What is the GroupID needed for parameters.

**Comment by taarskog** [comment]
It is the id of the power bi **app workspace** containing your report/dashboard. Remove it if embedding a personal view (from _My Workspace_).

If you use the configuration page to copy the config parameters you get that id automatically. See http://crm-powerbi-viewer.heiigjen.com/pages/add-view-to-dashboard.html


**Fun(?) fact:** In your list of workspaces you will also see Microsoft Teams you are a member of. Also the name groupId comes from workspaces being groups in Azure Active Directory and this is their id.
