### ISSUE TITLE
Azure AD -> Grant Permissions

### ISSUE THREAD

**Issue by tpcorcoran** [taarskog/crm-powerbi-viewer#33]
This is more of a question than an issues.  We have successfully used your solution to embed PowerBI elements into a Microsoft Dynamics form.  The problem we are having now is that a Dynamics user can only see the embedded elements if they go into Azure AD and click the Grant Permissions button.  Obviously this is not feasible due to a large number of users, so is there a way to grant permissions on behalf of other users?  

We did have an Azure Global Admin user go in and click the Grant Permissions button, but that didn't seem to resolve the issue.  I understand if this is getting outside of your area of expertise, but wanted to make sure we weren't missing something with the app configuration.

Thanks,
Tim

**Comment by taarskog** [comment]
Hi Tim,

That's strange. Having an admin grant access should be sufficient for all users in the tenant ref. bullet 6 at https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v1-integrate-apps-with-azure-ad#example-of-the-consent-experience.

I suggest you enable verbose adal logging by setting `auth_log_level: 3,` in config.js. Maybe that will provide hints on what might be the issue.

**Comment by taarskog** [comment]
Could you also verify that you remembered to update the manifest and set `"oauth2AllowImplicitFlow": true,`? Ref step 17 at http://crm-powerbi-viewer.heiigjen.com/pages/azure-ad.html

**Comment by taarskog** [comment]
Hi Tim. Great to hear you found a solution.

Appreciate that you shared your findings.

-Trond
