### ISSUE TITLE
401: Unauthorized-Error:null

### ISSUE THREAD

**Issue by chikhalenakush** [taarskog/crm-powerbi-viewer#35]
I created Azure AD (with all the permissions, manifest update), Configured powerbi/scripts/config.js with correct Application Id. I get 401 Error. Is there anything I am missing

**Comment by taarskog** [comment]
Probably ;-), but hard to say with so little information. First try to log in to Power BI directly (https://app.powerbi.com). If that works retry opening the solution configuration view.

Next set logging levels to verbose (both for the app and adal). Check if you find any obvious issues...

Lastly post your configuration, and screenshots of the console log and AD-permissions+manifest here.

**Comment by taarskog** [comment]
Forgot the most important - your power bi license. See #23.

**Comment by chikhalenakush** [comment]
Thanks it worked. There were 2 Issues.

1. I did not had powerBI account.
2. No power bi Pro license.
