### ISSUE TITLE
Reports not listed in configuration page after changing D365 URL

### ISSUE THREAD

**Issue by taarskog** [taarskog/crm-powerbi-viewer#38]
The IT department decided to rename the D365 URL for security reason. We experienced issues by just updating the URL in the Azure Active Directory, so, we unregistered and re-registered the app. However, the issue of "No Reports Found" happened again, and this time the reports didn't show up the next day (like last time). We went through the all the installation steps to make sure we didn't miss anything.

Any suggestions?

![screenshot](https://user-images.githubusercontent.com/43156216/45643747-9f81fd80-ba70-11e8-9b47-29ebce3b6ca9.png)

Thanks!

_Originally posted by @ForTheLoveOfD365 in https://github.com/taarskog/crm-powerbi-viewer/issues/36#issuecomment-422131554_

**Comment by ForTheLoveOfD365** [comment]
Thank you for responding!

For example, the URL was https://XYZInc.crm.dynamics.com, but the IT department felt that by having company name (XYZ Inc.) in the URL could be a risk. So, they changed it.

We tried clearing out browser caches and cookies, but still weren't able to see the reports. 

The admin went into the Azure Active Directory, and found out that the initial registration was still there and the client id was still being used. After the admin cleared out the duplicate registration, everything showed up correctly.
