### ISSUE TITLE
Add support for filter

### ISSUE THREAD

**Issue by taarskog** [taarskog/crm-powerbi-viewer#4]
Power BI supports getting a single filter either as an encoded part of the url query
> ```html
   filter=<table>/<column> eq '<filtervalue>'
```

or by passing the filter as odata in the postmessage when providing the token
> ```js
iframe.contentWindow.postMessage(JSON.stringify({
   oDataFilter: "<table>/<column> eq '<filtervalue>'"
   action: "loadReport",
   accessToken: token,
   width: width,
   height: height }), "*");
```

Add support for static filters on dashboards and dynamics filters from form data (Xrm) when embedding reports into CRM forms.

Filters currently only supported on reports and only a single filter can be set.

**Comment by detritusau** [comment]
Top on my wishlist

**Comment by taarskog** [comment]
In 5b6fd80 I have added support for a new CRM data parameter named *filterFn*. The function referenced by FilterFn must return a valid filter and should be placed in powerBiConfig.js. By supporting a custom function it is possible to get/construct the filter however the user wants - i.e. by using Xrm or calling other services.

**New parameter construct for reports is then:**
`type=report&reportId=<reportId>[&groupId=<groupId>][&filterFn=<nameOfFunc>]`

**And in powerBiConfig.js the func could be:**
(here \<nameOfFunc\> is opportunityFilter)
```js
function opportunityFilter() {
	var filter = "OpportunitySet/Status eq 'Won'";
	return filter;
}
```

**Comment by taarskog** [comment]
In 85d617a8 I have added support for a second new CRM data parameter named *filter*. Using this a Power BI filter can be specified with replacement parameters. The current record id, name, and all attributes on the form can be used as parameters.

```
 type=report& ... [&filter=<table>/<column> eq '{{<logicalname>[#<format>]}}'
```
where
**table** and **column** is the table and column in Power BI to filter.
**logicalname** is the logical name of the CRM attribute to add as filter value
**format** is an optional parameter for record id, lookups and optionsets that makes it possible to define if you want to use the attribute value (default and no format value should be added) or text (**#F**) as parameter. For lookups the entity logicalname can also be set (**#T**).

The sample below replaces `'{{statecode#F}}'` with 'Open' when the opportunity is Open.
```
filter=OpportunitySet/Status eq '{{statecode#F}}'
```

You reference the active record by using **id** as the logicalname.

filterFn takes precedence if both filterFn and Filter is specified.
