### ISSUE TITLE
Configuration screen is blank

### ISSUE THREAD

**Issue by FrederickLecavalier** [taarskog/crm-powerbi-viewer#40]
**Describe the bug**
Trying to open the configuration page within the solution but the screen is blank

![image](https://user-images.githubusercontent.com/41200862/46417019-c12ce700-c6f6-11e8-88df-fcb69c2f754c.png)

**To Reproduce**
1. Install / Configure the solution 
2. Click on the "configuration" link within the solution
3. Screen is blank

**Expected behavior**

**Screenshots**
If applicable, add screenshots/files to help explain your problem (including screenshot/logfile of console log). For configuration and JavaScript issues please also include `his_/powerbi/scripts/config.js`

**Environment (please complete the following information):**
 - D365CE Online 
 - Browser Chrome
 - D365CE version [e.g. 9.0.2.2725]
 - crm-powerbi-viewer version [e.g. 1.1.0]
 - Are you able to log directly into [Power BI](https://app.powerbi.com) and see your report/dashboard? Yes

**Additional context**

**Comment by FrederickLecavalier** [comment]
I tried in Internet Explorer and got a popup asking to give permission.  Went back to chrome and got this error message 

![image](https://user-images.githubusercontent.com/41200862/46419277-8a0d0480-c6fb-11e8-85db-e299fe9847c8.png)

How can I diagnose this error message ?

Thanks

**Comment by taarskog** [comment]
Probably an issue with the manifest. Please verify that you have performed (and saved) changes as described on step 17-18 at http://crm-powerbi-viewer.heiigjen.com/pages/azure-ad.html.

If you followed the simple flow it is step 10-11 (see http://crm-powerbi-viewer.heiigjen.com/pages/azure-ad-simple.html).

**Comment by taarskog** [comment]
No response in 6+ weeks. Closing as this is known to be working on a properly configured environment.
