### ISSUE TITLE
Question: Keep the report level filter when bookmarks are applied

### ISSUE THREAD

**Issue by ForTheLoveOfD365** [taarskog/crm-powerbi-viewer#41]
Hi Trond,

I have 6 bookmarks that hide/show 6 different data tables on a report. The script I was working on would only apply the report level filter to the default table/first table. The report level filter would go away after I clicked on different bookmarks. How could I keep the report level filter when bookmarks are applied?

Samples.Filters.filterOnOwnerName = function (report) {
    report.on("loaded", function(event) {       

	var username = window.parent.Xrm.Page.context.getUserName();
	console.log(username);

            const filterUserName = {
                $schema: "http://powerbi.com/product/schema#basic",
                target: {
                    table: "filteredpayment",
                    column: "Rep"
                },
                operator: "In",
                values: [username]
            };
            report.setFilters([filterUserName]); 
	
});
}

Thank you!

**Comment by taarskog** [comment]
Hi,

I expect listening to the event **bookmarkApplied** will work... 

You can find more information on this at https://github.com/Microsoft/PowerBI-JavaScript/wiki/Bookmarks

**Comment by taarskog** [comment]
Hi,

I expect listening to the event **bookmarkApplied** is what you need.

You can read more on this at https://github.com/Microsoft/PowerBI-JavaScript/wiki/Bookmarks

**Comment by taarskog** [comment]
No response in 3+ weeks. Assuming handled by using suggested event.
