### ISSUE TITLE
Uncaught Get pages is not supported while embedding a visual.

### ISSUE THREAD

**Issue by jefffenn** [taarskog/crm-powerbi-viewer#42]
**Describe the bug**
Attempting to filter a visual after render, and receiving the error:
_**Uncaught Get pages is not supported while embedding a visual.**_

The error occurs when trying to make a call to report.GetPages().  Need to do this in order to set the active page and get the active visual.

**Sample Code**
Here is my sample code.  Even if I comment out most of the code, I still get the error.

Samples.Filters.filterOnSurgeonVisual = function (report) {

      const filter = {
                          $schema: "http://powerbi.com/product/schema#basic",
                           target: {
                                   table: "Surgeons",
                                   column: "SURGEON_ID"},
                           operator: "Eq",
                           values: ["4000047"]
                   }
     //alert("test");
     console.log('filterOnSurgeonVisual Start');
  
     let filteredSet = false;

     report.on("rendered", () => {
             if (filteredSet) return;
             filteredSet = true;
             report.getPages()
                  .then(function (pages) {
                       //Retrieve active page
                       //var activePage = pages.find(function (page) {
                       //      return page.isActive
                       //});
                       console.log("filterOnSurgeonVisual Page Name: " + activePage.name);
                       /*
                       activePage.getVisuals()
                        .then(function(visuals) { 
                            // Retrieve the wanted visual
                            var visual = visuals.find(function(visual) {
                                return visual.name = "229533d51970d8bb65cd";
                            });
                            visual.setFilters([filter])
                                .then(function() {
                                    console.log("Filter Set");
                                })
                                .catch(function (errors) {
                                    console.log(errors);
                                })
                        })
                        .catch(function (errors) {
                            console.log(errors);
                        });
                        */
                    })
                    .catch(function (errors) {
                        console.log("Error Getting Pages")
                        console.log(errors);
                    });
                    
        }); // rendered
  
}

**Expected behavior**
Not receive the error and be able to filter the visual on my desired column.

**Comment by jefffenn** [comment]
Additional screen shot that may help:
![error](https://user-images.githubusercontent.com/19962776/47230613-8c1fc600-d37f-11e8-9fd9-bcced1885bcf.jpg)

**Comment by taarskog** [comment]
Kind of makes sense as pages are hidden when embedding a single visual.

In [v1.2.0-beta](https://github.com/taarskog/crm-powerbi-viewer/releases/tag/v1.2.0-beta) I have created a new parameter named **filterFn**. Appreciate if you can verify that this solves your issue by changing from using customFn to filterFn and update your code to something like the following:

```js
window.Samples = window.Samples || {};
Samples.Filters = Samples.Filters || {};
Samples.Filters.filterOnSurgeonVisual = function () {
    return [
        {
            $schema: "http://powerbi.com/product/schema#basic",
            target: {
                table: "Surgeons",
                column: "SURGEON_ID"
            },
            operator: "Eq",
            values: ["4000047"]
        }
    ];
}
```

Added bonus is that the code becomes a lot simpler.

**Comment by taarskog** [comment]
Closing as no feedback in 3+ weeks - have tested and verified a similar scenario.

**Comment by GloriaOliveras** [comment]
With this post i got to filter my Power BI report in Dynamics 365 account form.

I need to filter by the value of a field on the page. 

Thanks in advance for your help.
