### ISSUE TITLE
Question re licensing

### ISSUE THREAD

**Issue by colinsherry** [taarskog/crm-powerbi-viewer#43]
As you appear to be using Power BI embedded does this application need a Power BI capacity SKU or, given that you can already embed tiles, is this included in the dynamics 365 license.

Thanks

**Comment by taarskog** [comment]
No I do not use [_Power BI Embedded_](https://docs.microsoft.com/en-us/power-bi/developer/embedding#embedding-for-your-organization). This is [_Embedding for your organization_](https://docs.microsoft.com/en-us/power-bi/developer/embedding#embedding-for-your-organization).

You need Power BI Pro/Premium to share reports (#25 and #30). I'm not a licensing expert but my understanding is that if you have Pro when sharing the viewers also need a Pro license. However if the one sharing has Premium the viewers do not need a Pro license. Please refer to the official docs for the official answer: https://docs.microsoft.com/en-us/power-bi/service-admin-licensing-organization.
