### ISSUE TITLE
login.microsoftonline.com refused to connect.

### ISSUE THREAD

**Issue by SilviaTeixeira** [taarskog/crm-powerbi-viewer#47]
I'm not sure about what went wrong. I get the error login.microsoftonline.com refused to connect.
I added the users as owners. Do I need another permission ?

**Comment by SilviaTeixeira** [comment]
I mean..If I go to my azure and add the app and try to see the application, it works. But if another users try to do that, it does not work. I've added the user as owner of the app too

**Comment by taarskog** [comment]
Make sure you have followed _**all**_ steps in the installation guide. This is the most common root cause.

Then verify that the other users are licensed for Power BI and that they can access these reports directly from within Power BI.

**Comment by taarskog** [comment]
Just re-read this issue. You probably need to grant permissions to all users. My guess is that you are not admin and thus are not allowed to grant permissions to all users. Ask an admin of Azure AD to grant permissions to everyone for you.

You need help from an admin if you get this message after granting permissions 

> Successfully granted permissions to the application for your account. To grant permissions for all users, please have an admin consent to the application.

**Comment by taarskog** [comment]
Assumed fixed (no response in 3-4 weeks).
