### ISSUE TITLE
Importing Solution in CRM online V2015 

### ISSUE THREAD

**Issue by lagrottan** [taarskog/crm-powerbi-viewer#5]
it appears the solutions are for CRM Online 2016.   Will this only work in CRM online 2016, or would this plugin also work in CRM 2015?  When I try to import into CRM online 2015 I get an error about only being able to import solutions with version 7 or earlier.  The current plugin is V8 (ie CRM online 2016).

**Comment by taarskog** [comment]
True that it is created on the latest version on CRM Online, but should work fine on earlier versions.

Approach would be to build the solution (***gulp task DIST***) and add the files placed under ./artifacts/dist to a solution in your environment

The lifespan of 2015 on Online is limited, but I'll look into creating a solution for it.

**Comment by taarskog** [comment]
Fixed in release v0.3.0 (ef5b392).
