### ISSUE TITLE
Filter error

### ISSUE THREAD

**Issue by JacobHonig** [taarskog/crm-powerbi-viewer#50]
Hi

I have created a report with data from AX. I use the accountnumber on account in CRM as key to the customer (User ID) in AX. 

The script takes accountnumber from the account form and pass it as filter value

```
window.Samples = window.Samples || {};
Samples.Filters = Samples.Filters || {};

Samples.Filters.filterWarrentyUnit= function () {


    var accnum = window.parent.Xrm.Page.getAttribute("accountnumber").getValue();

    return [
        {
            $schema: "http://powerbi.com/product/schema#basic",
            target: {
                table: "Warrenty Units",
                column: "User ID"
            },
            operator: "Eq",
            values: [accnum]
        }
    ];
}
```
The report is showing fine, but is not filtered.

![image](https://user-images.githubusercontent.com/44808035/48612232-ab167580-e988-11e8-83bc-2e96cb4c4db5.png)

Do you have any idea why i get this error?

**Comment by taarskog** [comment]
Could it be that `accnum` is of invalid type? Suggest you log the filter to the console to verify that it looks as expected. 

Something like:
```js
window.Samples = window.Samples || {};
Samples.Filters = Samples.Filters || {};

Samples.Filters.filterWarrentyUnit= function () {


    var accnum = window.parent.Xrm.Page.getAttribute("accountnumber").getValue();

    let filter = [
        {
            $schema: "http://powerbi.com/product/schema#basic",
            target: {
                table: "Warrenty Units",
                column: "User ID"
            },
            operator: "Eq",
            values: [accnum]
        }
    ];

    console.log(filter);
    return filter;
}
```

**Comment by JacobHonig** [comment]
Hi, it was totally my own mistake. I had misspelled the table name. 

Thank you for you help anyway :)
