### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by JacobHonig** [taarskog/crm-powerbi-viewer#51]
Hi

I need to print the report from D365. How would you do that? It is ok if it is just a link to open the report in Power BI.

**Comment by taarskog** [comment]
The report object has a method for printing. Take a look at https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embedding---Basic-interactions#print-a-report

I would probably add a button on the report for printing and add a listener for onclick in the custom function.

**Comment by JacobHonig** [comment]
I'm not very good at JavaScript. How would you add a button to the report?

**Comment by JacobHonig** [comment]
Hi i figured it out. The button was in an iframe, that i needed to find first 

```
    var frm = window.parent.document.getElementById('WebResource_PrintAccountDetailsButton');
    var btn= frm.contentWindow.document.getElementById('btnPrintReport');
    btn.addEventListener("click", function() { report.print(); });

```

Now i can print the report in CRM :)
