### ISSUE TITLE
Is there an issue with multiple users as administrator?

### ISSUE THREAD

**Issue by systamper** [taarskog/crm-powerbi-viewer#52]
**Describe the bug**
Not sure if this is an issue. We have multiple user who will be setting up and configuring dashboards from a variety of shared workspaces. Someone else configured the solution. We have multiple system administrators. When I went in to view the dashboard he configured, it did not show up for me. And when I went to the configuration page for the solution, none of the dashboards or reports appeared for me. Again, this worked for the person who set it up, so I am wondering if there is an issue of having multiple users configuring the system. 

**To Reproduce**
1. Go to the solution customization page
2. Expect to see the app workspaces, dashboards, and reports.

**Screenshots**
![screenahot](https://user-images.githubusercontent.com/26444056/49023644-a8283b80-f165-11e8-83be-171b24213ed6.jpg)

**Environment (please complete the following information):**
 - D365CE hosting: online
 - Browser safari
 - D365CE version 9.1.0.643
 - crm-powerbi-viewer version downloaded 11/20/18
 - Are you able to log directly into [Power BI](https://app.powerbi.com) and see your report/dashboard? yes

**Comment by taarskog** [comment]
Expect this to be similar to what I commented [here](https://github.com/taarskog/crm-powerbi-viewer/issues/47#issuecomment-439496955). Probably an issue with step [15b](http://crm-powerbi-viewer.heiigjen.com/pages/azure-ad.html) not being performed by an AD admin.

**Comment by systamper** [comment]
Thanks, @taarskog! This is still not working. The admin has checked all the "Delegated Permissions" that have the word _View_ in them. However, he said that when he tried checking the "View All Content in Tenant" option, it would not save and reverted back to it not being selected. Here is a screenshot of everything selected. An other thoughts?  
![power bi viewer - all but view all in tenant selected](https://user-images.githubusercontent.com/26444056/49084297-0b28d980-f21d-11e8-9d73-1c5d2eb287c9.jpg)

**Comment by taarskog** [comment]
_View All Content in tenant_ is not required. Sorry, but I'm still not convinced all steps have been followed (this is confirmed working for multiple users in other tenants). Can you have the admin confirm (with a screenshot) the message he gets after pressing [Grant Permissions] as described in step [15b](http://crm-powerbi-viewer.heiigjen.com/pages/azure-ad.html)?

**Comment by mawaisaslam** [comment]
does it require any Power BI embedded capacity?

**Comment by taarskog** [comment]
No, but it does require Pro/Premium licenses - see #43.

**Comment by mawaisaslam** [comment]
Hello, taarskog thanks for the solution its really handy and easy to use. Nevertheless, I am getting peculiar behavior of this solution it sometimes renders report perfectly and sometimes just show a blank page. and it's not working with I.E

![image](https://user-images.githubusercontent.com/15087139/50135043-904f5d80-02b4-11e9-9cbc-a0e324fb1ec7.png)

**Comment by taarskog** [comment]
Hi mawaisaslam. As this is not related to the current issue please open a new issue. Remember to provide details of your environment including version numbers and a screenshot of the console log. Describe the situtations where you get the blank screen in detail (has it been a while since the last authentication, does it work after refreshing the screen [CTRL-F5], etc...). Also set the logging levels to DEBUG to catch all relevant messages).

Re IE power BI supports version 11 (see https://docs.microsoft.com/en-us/power-bi/consumer/end-user-browsers).
