### ISSUE TITLE
How can I diagnose Power BI Viewer filter issues

### ISSUE THREAD

**Issue by BSuycott** [taarskog/crm-powerbi-viewer#53]
In following the examples in advanced configuration, I can't tell if the filter code is actually getting loaded and is failing, or if the code is simply not loading.  I know that the filter criteria I am using if viable as I am attempting to replace an existing call to Power BI from a webresource button that included a filter using the entity/fieldname eq value format code fragment looks like below - have hardcoded the value to filter on to remove doubt, but ultimately would replace "21" with entityid variable obtained from the Dynamics account form:
window.PowerBIViewer = window.PowerBIViewer || {};
PowerBIViewer.Filters = PowerBIViewer.Filters || {};

PowerBIViewer.Filters.filterOnEntityNumber = function (report) {
       report.removeFilters();
       //var entityid = Xrm.Page.getAttribute("accountnumber").getValue();      // Assumes we are on account page in CRM
       const filter = {
            $schema: "http://powerbi.com/product/schema#basic",
            target: {
                table: "Entity",
                column: "EntityNumber"
            },
            operator: "In",                                 
            values: ["21"]                                
        };
    page.setFilters([filter]);
  
}

Config webresource snippet:
![image](https://user-images.githubusercontent.com/45496990/49393449-e0e08b80-f6f6-11e8-81b2-7b9ca08705f0.png)

Form inclusion of the customFN filter:
&customFn=PowerBIViewer.Filters.filterOnEntityNumber

The Power BI report is showing, but it is not filtering, so I need a way to troubleshoot if the above filter code is occurring.

**Comment by taarskog** [comment]
A call to `console.log("...");` is a good way to verify that your code is loaded...

As to your code you are missing a critical peace:
`report.on("loaded", function (loadedEvent) {`
...Set your filter here...
`}`

**Comment by BSuycott** [comment]
Trond,

Thank you for your response – and even more so for a great solution to something that Microsoft seemed to have forgotten!

Your comments have enabled me to get further in the process.  What I am seeing in the console tracing right now is that it appears that the filter simply isn’t taking effect.  I am using report.setFilters([filter]) and console recording shows that it appears to set the values properly in the filter, and the setFilter call doesn’t create an error.   I have also tried the page.setFilters, neither of the filtering attempts shows an error, but neither do they take effect.
[cid:image002.png@01D48BC4.5A56DD00]

To try to remove the complexity within the dot notation, I changed the entirety of the filter code to the following (this is the entire contents of the webresource), and based on the above console log it does appear to be executing:

function filterOnEntityNumber(report) {
    console.log('filterOnEntityNumber loaded');
    report.on("loaded", function (loadedEvent) {
        console.log('pbi loaded about to remove filters');
        //report.removeFilters();
        var entityid = window.parent.Xrm.Page.getAttribute("accountnumber").getValue();      // Assumes we are on account page in CRM
        console.log('entityid=' + entityid );
        const filter = {
            $schema: "http://powerbi.com/product/schema#basic",
            target: {
                table: "Entity",
                column: "EntityNumber"
            },
            operator: "In",
            values: [entityid]
        };
        console.log('filter created content follows');
        console.log(filter);
        console.log('attempting to set filter now');
        try {
            report.setFilters([filter]);
            console.log('filter set complete');
        } catch (err) { console.log('error caught='); console.log(err); }
    });
}

Outside of your functionality I am able to call this report from a button on the form, and the filter that I pass on the URL appears as follows (I assume the filter on the URL line is at the report level as all pages within the report are then filtered by the value of the account number – aka entityid – that is passed in):

function callPBIReport() {
    var entityid = Xrm.Page.getAttribute("accountnumber").getValue();
    var url1 = 'https://app.powerbi.com/groups/XXXXXXXXXXXXXXX/reports/yyyyyyy/ReportSection02cf72fd344e33a01bee';
        url1 = URL1 + '?filter=Entity/EntityNumber eq ';
    var url = url1 + entityid;
    window.open(url, null, 900, 1400, true, false, null);

}

If I manually navigate to the report, I can also append the URL with ?filter=Entity/EntityNumber eq 21 and the report will render with the filtering.

I get the feeling I am very close here, but just missing one or two key elements to getting the filtering to work properly.

Regards,

Bill

**Comment by taarskog** [comment]
I believe (not 100% sure) that the query parameters you pass in are **page level filters**. Suggest you verify that the fields are specified as **report level filters**:
![image](https://user-images.githubusercontent.com/609765/49538735-66696480-f8cc-11e8-8af3-6d9f23b96aff.png)

Also take a look at the [sample code](https://github.com/taarskog/crm-powerbi-viewer/issues/39#issuecomment-432809783) I provided on a previous issue.

**Comment by BSuycott** [comment]
Trond,

I also tried it as a page.setFilter – both give the appearance of not failing, but not impacting the outcome either from the report.  Not sure if there is other diagnostics that can be used to view what actions are occurring within Power BI to try to understand why the filters aren’t having an effect (i.e. how to see if the filters are actually being pushed in  - there are no errors thrown by the calls).

Regards,
Bill

**Comment by taarskog** [comment]
You will not catch any errors with your current try/catch as the setFilters method is async. See how I catch errors in the sample code I linked to in my prev comment.

Another option to test is the new way of setting filters introduced in [v1.2.0-beta](https://github.com/taarskog/crm-powerbi-viewer/releases/tag/v1.2.0-beta).

**Comment by BSuycott** [comment]
Trond,

Thank you for the tips on troubleshooting.  Ultimately the problem was resolved by changing from a basic filter to an advanced one for this report.    At least in the case of the report that I am working with, the advanced filter works for both page and report level.  Have included a sample of one of the filters that are working under the current non-beta version of PowerBIViewer.

function filterOnEntityNumber(report) {
    report.on("loaded", function (loadedEvent) {
    // console.log(report.getFilters());   // Inspect current filters on report level
    var entityid = null;
        try {
            entityid = parent.Xrm.Page.getAttribute("accountnumber").getValue();
        } catch (err) { console.log(err); }
        const filter = {
            $schema: "http://powerbi.com/product/schema#advanced",
            target: {
                table: "Entity",
                column: "EntityNumber"
            },
            logicalOperator: "And",
            conditions: [
                {
                    operator: "Is",
                    value: entityid
                }
            ],
        };
        try {
            report.setFilters([filter]);
        } catch (err) { console.log(err);}
    });
}

Look forward to your next release.

Thanks again for your assistance and for creating this much needed product.

Regards,

Bill Suycott
FIS
