### ISSUE TITLE
Issue showing on configuration page

### ISSUE THREAD

**Issue by achandler2033** [taarskog/crm-powerbi-viewer#54]
Hey Trond,

First of all, amazing work. I really appreciate all that you have done. I have read through all the completed issues and did all that was stated in those responses.

I double checked the manifest and properly executed step 17 and 18 in the guide. I also ensured that the client-id was properly placed in quotations inside the config. file. Here are some screen shots

The error:

![image](https://user-images.githubusercontent.com/43383154/50116398-08b41100-0218-11e9-9225-4f5892a51d63.png)

The manifest:

![image](https://user-images.githubusercontent.com/43383154/50116441-2e411a80-0218-11e9-8bb2-8fb019de76f7.png)

The config file:

![image](https://user-images.githubusercontent.com/43383154/50116494-5df02280-0218-11e9-990e-377b166a1f9f.png)

The debug console with the client-id error:

![image](https://user-images.githubusercontent.com/43383154/50116564-7ceeb480-0218-11e9-8ab8-862d663dd222.png)

I am wondering why there is an issue as I feel like I have done everything properly according to the instructions. 

Best,

Austin

**Comment by taarskog** [comment]
As the 2nd error is saying your config.js is not correct. It is saying unexpected equal sign (=) so it is that or an issue with brackets/commas.

**Comment by taarskog** [comment]
Take a look at the sample functions at http://crm-powerbi-viewer.heiigjen.com/pages/advanced-config.html

Or if using v1.2 check out https://github.com/taarskog/crm-powerbi-viewer/issues/42#issuecomment-432404083
