### ISSUE TITLE
Group based reports/dashboard result in "This content is not available"

### ISSUE THREAD

**Issue by lagrottan** [taarskog/crm-powerbi-viewer#6]
Greetings,

I have been working with this plugin the last few weeks, and at some point any report/dashboard published to a group will not render within CRM (2015 May update).  Reports/Dashboards published to the users My Workspace render fine.   The user account I test with has the correct licensing (Power Bi Pro, Azure AD premium, CRM Pro).  

I have confirmed this on 2 different tenants.

Did something change on the Microsoft side?  Any help would be appreciated.  I attached a screenshot of what is happening.

![issue](https://cloud.githubusercontent.com/assets/15945743/15301546/28d742ca-1b7c-11e6-86bc-3e2f46997db2.png)

**Comment by taarskog** [comment]
My bad. Forgot to add proper links in the configuration page. Fixed in release v0.3.1 (a6b1710).
