### ISSUE TITLE
DOMException: Failed to execute 'postMessage' on 'Window' on report.applyTheme

### ISSUE THREAD

**Issue by evanbarke** [taarskog/crm-powerbi-viewer#67]
Good day!

I am trying to build in a day/night switch into my Power BI Embedded app that will flip from dark to light. I want to extend the functionality into the embedded report itself.

Here is the code:

` var report = powerbi.embed(reportContainer, config);
                           $.ajaxSetup({
                                async: false
                            });
                           var themeJson=  (theme == "material") ? $.getJSON("Content/power-bi-themes/light.json") : $.getJSON("Content/power-bi-themes/dark.json");
                            $.ajaxSetup({
                                async: true
                            });

                            report.applyTheme({themeJson:themeJson});`

The error I am getting is in the subject line. Please help! :)

**Comment by taarskog** [comment]
Hi.

This is not related to crm-powerbi-viewer so posting here is not the right place to get answers on using the PowerBI-JavaScript library. Even so I've would have tried to help you, but do not have capacity to look into this before Christmas Holidays.

I recommend looking at samples on https://github.com/Microsoft/PowerBI-JavaScript/wiki/Apply-Report-Themes and/or posting your issue on https://community.powerbi.com/t5/Developer/bd-p/Developer.

-Trond

**Comment by evanbarke** [comment]
Hi there Trong,

Yes I'm sorry. I realised that after posting. I just saw Github and thought
I was in a public place haha.

My apologies. Have a lovely holiday.

I have posted on the power BI community forum (developer section).

Cheers!
Evan
