### ISSUE TITLE
If Power BI dashboard is the default dashboard the dashboard isn't loaded

### ISSUE THREAD

**Issue by detritusau** [taarskog/crm-powerbi-viewer#7]
Steps to reproduce:
- Go to Sales - Dashboards
- Make a Power BI dashboard the default dashboard
- Log off and log on -> the report isn't loaded. Refreshing the view with F5/Reload fixes this
Expected result: the report is loaded automatically

**Comment by taarskog** [comment]
Fixed in release v0.3.1 (a6b1710)
