### ISSUE TITLE
Redirect URL

### ISSUE THREAD

**Issue by fauves** [taarskog/crm-powerbi-viewer#79]
Hi,
I have been having some issues related to RedirectURL. I've done all the steps and added RedirectURL to the azure, but I keep getting the error. Is there any field to configure the url in the powerbi viewer? What am I doing wrong? I think the redirecturl I put is the correct one.
Error:
![image](https://user-images.githubusercontent.com/29117266/103377046-30603400-4ad6-11eb-900d-376b46485ee3.png)
RedirectURL the same as my crm link
![image](https://user-images.githubusercontent.com/29117266/103377075-48d04e80-4ad6-11eb-82a4-7ceb27c0d996.png)

**Comment by taarskog** [comment]
Hi,

Most have historically used crm-powerbi-viewer to embed reports - as this was not supported by Microsoft when I created the solution. I assume - based on lack of questions around it - that there have been little usage of one the real powers of crm-powerbi-viewer, which is the ability to filter and add logic based on data from the record where a PowerBI report has been  embedded.

If you are in the same situation as most - i.e. you simply need to add a Power BI dashboard or report as system dashboard in CE, then I recommend you first consider the [new out-of-the-box support](https://powerapps.microsoft.com/en-us/blog/power-bi-embedded-as-system-dashboard-in-model-driven-apps-preview/) that is in public preview. It will be your best option for simple embedding.

If you still think crm-powerbi-viewer is the right choice I suggest you take a new look at the guide for Azure AD found on (1) in the [installation steps](http://crm-powerbi-viewer.heiigjen.com/#installation-steps) and make sure you have followed all steps.

From the image I see that the URI is missing * at the end of the URI as described on step 5 in the original guide (new validation added by MS may require you to update the URI directly in the manifest).

Good luck and thank you for looking into crm-powerbi-viewer.

-Trond

**Comment by fauves** [comment]
Hi,

I really appreciate the quick response. I fixed the error by adding * in both Urls.
Now I am getting this 401 error, what could it be?
I will also follow the embed suggestion that you indicated, thank you very much.

![image](https://user-images.githubusercontent.com/29117266/103385074-dfaa0480-4af0-11eb-9bf0-a2c0cb3735ad.png)

**Comment by taarskog** [comment]
Probably something to do with Power BI licensing or permissions - verify that you can log into powerbi.com and verify step 15 on the original Azure AD guide. For details look at the [other issues on 401](https://github.com/taarskog/crm-powerbi-viewer/issues?q=401).

**Comment by fauves** [comment]
It was permissions issues the 401. Thanks a lot! Happy new year!
