### ISSUE TITLE
Integration Question - App URL Support

### ISSUE THREAD

**Issue by MUConcepts** [taarskog/crm-powerbi-viewer#82]
Hello,

I've got a simple question about the Power Bi Viewer. It works great with workspace URL formatted with a GroupId "Guid".

Here we are facing a case where the Organization is going under **Power BI Premium** and will use the "App" functionnality. So the Report URL will looks like something like this : 

https://app.powerbi.com/groups/**me**/apps/"AppGuid"/reports/"ReportGuid"/ReportSectione7********?ctid="ctIdGuid"

In this scenario the user should have access to the reports with a Free licence. 

Could you tell me if this is supported and how the URL can be integrated ? 

Thanks in advance for your feedback,

Kind Regards,

Michaël

**Comment by taarskog** [comment]
Hi Michaël,

Not sure if it works in your case, but have you considered the built-in functionality from MS for embedding reports? 

Apps not supported by my code ATM, but should be a simple fix. Let me know if you cannot use OOB-functionality from MS - I may be able to take a look at it next week. No promises so the quicker approach would be to send me a pull request...

-Trond

**Comment by taarskog** [comment]
On second thought - I believe apps are already supported. They should appear under "Personal" in the Configuration view of Power BI Viewer. A future update may highlight these as apps, but for now you should be able to find them by their names...

![image](https://user-images.githubusercontent.com/609765/112769199-0f00dc80-9020-11eb-8c8a-a8cf04610555.png)

![image](https://user-images.githubusercontent.com/609765/112769228-335cb900-9020-11eb-87bb-51dba4508d40.png)
