### ISSUE TITLE
Dashboard with pinned live page

### ISSUE THREAD

**Issue by chernyeec** [taarskog/crm-powerbi-viewer#9]
Apparently it does not support dashboard with pinned live page. It just shows a spinning loading wheel when opened.  Will it be available in the next release? any tentative release date? Thanks.

**Comment by taarskog** [comment]
You cannot add a full dashboard. Is the question about showing a single tile? What live page are you trying to show?

Do you get any errors in the console (browser debug view)?

**Comment by taarskog** [comment]
Closed due to no feedback.
